### ISSUE TITLE
Convert to English

### ISSUE THREAD

**Issue by tadaspetra** [easemob/UIKit_Chatroom_flutter#1]
The [readme in the example](https://github.com/easemob/UIKit_Chatroom_flutter/blob/main/example/README.md) is not in English. 

Should the main Readme be english as well? https://github.com/easemob/UIKit_Chatroom_flutter/blob/main/README.md

**Comment by dujiepeng** [comment]
@tadaspetra  
https://github.com/easemob/UIKit_Chatroom_flutter/blob/main/example/README.md
thx.

**Comment by tadaspetra** [comment]
How about making the default README in the root english as well?

**Comment by dujiepeng** [comment]
@tadaspetra It has been modified, Thanks for the advice.
