### ISSUE TITLE
Can't run project

### ISSUE THREAD

**Issue by tadaspetra** [easemob/UIKit_Chatroom_flutter#2]
When I clone this repo and run `flutter pub get` there is no local folder `../../../../im_flutter_sdk` which is used in `pubspec.yaml`. 

I tried using the one on [pub.dev](https://pub.dev/packages/im_flutter_sdk) and this results in a bunch of errors in the project

**Comment by dujiepeng** [comment]
@tadaspetra  has been fixed and pubilshed to pub.dev
https://pub.dev/packages/chatroom_uikit
